export const OPEN_EDIT_MODAL_REQUEST = "OPEN_EDIT_MODAL_REQUEST";
export const OPEN_EDIT_MODAL_SUCCESS = "OPEN_EDIT_MODAL_SUCCESS";
export const OPEN_EDIT_MODAL_FAILURE = "OPEN_EDIT_MODAL_FAILURE";

export const OPEN_DELETE_MODAL_REQUEST = "OPEN_DELETE_MODAL_REQUEST";
export const OPEN_DELETE_MODAL_SUCCESS = "OPEN_DELETE_MODAL_SUCCESS";
export const OPEN_DELETE_MODAL_FAILURE = "OPEN_DELETE_MODAL_FAILURE";

export const CLOSE_EDIT_MODAL_REQUEST = "CLOSE_EDIT_MODAL_REQUEST";
export const CLOSE_EDIT_MODAL_SUCCESS = "CLOSE_EDIT_MODAL_SUCCESS";
export const CLOSE_EDIT_MODAL_FAILURE = "CLOSE_EDIT_MODAL_FAILURE";

export const CLOSE_DELETE_MODAL_REQUEST = "CLOSE_DELETE_MODAL_REQUEST";
export const CLOSE_DELETE_MODAL_SUCCESS = "CLOSE_DELETE_MODAL_SUCCESS";
export const CLOSE_DELETE_MODAL_FAILURE = "CLOSE_DELETE_MODAL_FAILURE";
